db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD
  volumes:
    - data/mysql:/var/lib/mysql
web:
  image: indiehosters/etherpad
  environment:
    - ETHERPAD_ADMIN_PASSWORD
    - ETHERPAD_ADMIN_USER=pierre@ozoux.net 
    - ETHERPAD_PORT=80
  volumes:
    - data/settings:/opt/etherpad-lite/var
  links:
    - db:mysql
